/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package caculadoraciienti;

/**
 *
 * @author santi
 */
public class jfrmCalcu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(jfrmCalcu.class.getName());

    
     private double num1,num2,res = 0.00 ;
     private boolean igual, ini = true, op1,op2;
      private String ope;
    public jfrmCalcu() {
        initComponents();
        this.setTitle("Calculadora");
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jteje = new javax.swing.JTextField();
        bt7 = new javax.swing.JButton();
        bt8 = new javax.swing.JButton();
        bt9 = new javax.swing.JButton();
        bt4 = new javax.swing.JButton();
        bt5 = new javax.swing.JButton();
        bt6 = new javax.swing.JButton();
        bt1 = new javax.swing.JButton();
        bt2 = new javax.swing.JButton();
        bt3 = new javax.swing.JButton();
        bt0 = new javax.swing.JButton();
        btmult = new javax.swing.JButton();
        btdiv = new javax.swing.JButton();
        btsum = new javax.swing.JButton();
        btres = new javax.swing.JButton();
        btodo = new javax.swing.JButton();
        btpoce = new javax.swing.JButton();
        btborr = new javax.swing.JButton();
        btrai = new javax.swing.JButton();
        btigual = new javax.swing.JButton();
        btdeci = new javax.swing.JButton();

        jButton4.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jButton4.setText("7");

        jButton12.setText("jButton12");

        jButton14.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jButton14.setText("*");

        jButton18.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jButton18.setText("AC");
        jButton18.addActionListener(this::jButton18ActionPerformed);

        jButton20.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jButton20.setText("AC");
        jButton20.addActionListener(this::jButton20ActionPerformed);

        jButton23.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jButton23.setText("^");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jteje.setEditable(false);
        jteje.setEnabled(false);

        bt7.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        bt7.setText("7");
        bt7.addActionListener(this::bt7ActionPerformed);

        bt8.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        bt8.setText("8");
        bt8.addActionListener(this::bt8ActionPerformed);

        bt9.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        bt9.setText("9");
        bt9.addActionListener(this::bt9ActionPerformed);

        bt4.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        bt4.setText("4");
        bt4.addActionListener(this::bt4ActionPerformed);

        bt5.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        bt5.setText("5");
        bt5.addActionListener(this::bt5ActionPerformed);

        bt6.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        bt6.setText("6");
        bt6.addActionListener(this::bt6ActionPerformed);

        bt1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        bt1.setText("1");
        bt1.addActionListener(this::bt1ActionPerformed);

        bt2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        bt2.setText("2");
        bt2.addActionListener(this::bt2ActionPerformed);

        bt3.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        bt3.setText("3");
        bt3.addActionListener(this::bt3ActionPerformed);

        bt0.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        bt0.setText("0");
        bt0.addActionListener(this::bt0ActionPerformed);

        btmult.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btmult.setText("*");
        btmult.addActionListener(this::btmultActionPerformed);

        btdiv.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btdiv.setText("/");
        btdiv.addActionListener(this::btdivActionPerformed);

        btsum.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btsum.setText("+");
        btsum.addActionListener(this::btsumActionPerformed);

        btres.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btres.setText("-");
        btres.addActionListener(this::btresActionPerformed);

        btodo.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btodo.setText("C");
        btodo.addActionListener(this::btodoActionPerformed);

        btpoce.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btpoce.setText("%");
        btpoce.addActionListener(this::btpoceActionPerformed);

        btborr.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btborr.setText("AC");
        btborr.addActionListener(this::btborrActionPerformed);

        btrai.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btrai.setText("√");
        btrai.addActionListener(this::btraiActionPerformed);

        btigual.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btigual.setText("=");
        btigual.addActionListener(this::btigualActionPerformed);

        btdeci.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btdeci.setText(".");
        btdeci.addActionListener(this::btdeciActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jteje, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(bt7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(bt8, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(bt9, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btodo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btborr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(bt4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(bt5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(bt6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btres, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(bt1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(bt2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(bt3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btsum, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(bt0, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btmult, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btdiv, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btigual, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(10, 10, 10)))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btpoce, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btrai, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                                .addComponent(btdeci, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jteje, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt8)
                    .addComponent(bt9)
                    .addComponent(btodo)
                    .addComponent(btborr)
                    .addComponent(bt7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bt5)
                        .addComponent(bt6)
                        .addComponent(btres)
                        .addComponent(bt4))
                    .addComponent(btpoce, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt1)
                    .addComponent(bt2)
                    .addComponent(bt3)
                    .addComponent(btsum)
                    .addComponent(btrai, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt0)
                    .addComponent(btmult)
                    .addComponent(btdiv)
                    .addComponent(btigual)
                    .addComponent(btdeci))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton18ActionPerformed

    private void btodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btodoActionPerformed
    String text=jteje.getText();
     if (text.length() > 1) {
         text = text.substring(0, text.length() - 1);
         jteje.setText(text);
         ini=true;
     }else{
         jteje.setText("0");
     }
    }//GEN-LAST:event_btodoActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton20ActionPerformed

    private void bt0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt0ActionPerformed
        if (ini == true){ 
            jteje.setText(""); 
            jteje.setText("0"); 
            ini=false; 
        }else{
            jteje.setText(jteje.getText()+"0");
        }
    }//GEN-LAST:event_bt0ActionPerformed

    private void bt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt1ActionPerformed
        if (ini == true){ 
            jteje.setText(""); 
            jteje.setText("1"); 
            ini=false; 
        }else{
            jteje.setText(jteje.getText()+"1");
        }
    }//GEN-LAST:event_bt1ActionPerformed

    private void bt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt2ActionPerformed
        if (ini == true){ 
            jteje.setText(""); 
            jteje.setText("2"); 
            ini=false; 
        }else{
            jteje.setText(jteje.getText()+"2");
        }
    }//GEN-LAST:event_bt2ActionPerformed

    private void bt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt3ActionPerformed
        if (ini == true){ 
            jteje.setText(""); 
            jteje.setText("3"); 
            ini=false; 
        }else{
            jteje.setText(jteje.getText()+"3");
        }
    }//GEN-LAST:event_bt3ActionPerformed

    private void bt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt4ActionPerformed
        if (ini == true){ 
            jteje.setText(""); 
            jteje.setText("4"); 
            ini=false; 
        }else{
            jteje.setText(jteje.getText()+"4");
        }
    }//GEN-LAST:event_bt4ActionPerformed

    private void bt5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt5ActionPerformed
        if (ini == true){ 
            jteje.setText(""); 
            jteje.setText("5"); 
            ini=false; 
        }else{
            jteje.setText(jteje.getText()+"5");
        }
    }//GEN-LAST:event_bt5ActionPerformed

    private void bt6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt6ActionPerformed
        if (ini == true){ 
            jteje.setText(""); 
            jteje.setText("6"); 
            ini=false; 
        }else{
            jteje.setText(jteje.getText()+"6");
        }
    }//GEN-LAST:event_bt6ActionPerformed

    private void bt7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt7ActionPerformed
        if (ini == true){ 
            jteje.setText(""); 
            jteje.setText("7"); 
            ini=false; 
        }else{
            jteje.setText(jteje.getText()+"7");
        }
    }//GEN-LAST:event_bt7ActionPerformed

    private void bt8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt8ActionPerformed
        if (ini == true){ 
            jteje.setText(""); 
            jteje.setText("8"); 
            ini=false; 
        }else{
            jteje.setText(jteje.getText()+"8");
        }
    }//GEN-LAST:event_bt8ActionPerformed

    private void bt9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt9ActionPerformed
        if (ini == true){ 
            jteje.setText(""); 
            jteje.setText("9"); 
            ini=false; 
        }else{
            jteje.setText(jteje.getText()+"9");
        }
    }//GEN-LAST:event_bt9ActionPerformed

    private void btdeciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btdeciActionPerformed
        if(jteje.getText().contains(".")){
        }else{
            jteje.setText(jteje.getText()+".");
            ini=false;
        }
    }//GEN-LAST:event_btdeciActionPerformed

    private void btsumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsumActionPerformed
        igual=true;
        ini=true;
        if (op1=true){
            num1=Double.parseDouble(jteje.getText());
            jteje.setText(jteje.getText()+"+");
            op1=false;
        }else{
            if (op2=true){
            num1=Double.parseDouble(jteje.getText());
            jteje.setText(jteje.getText()+"+");
            op2=false;
        }else{
                jteje.setText(jteje.getText()+"+");
            }
        }
       ope = "+";
        
    }//GEN-LAST:event_btsumActionPerformed

    private void btresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btresActionPerformed
        igual=true;
        ini=true;
        if (op1=true){
            num1=Double.parseDouble(jteje.getText());
            jteje.setText(jteje.getText()+"-");
            op1=false;
        }else{
            if (op2=true){
            num1=Double.parseDouble(jteje.getText());
            jteje.setText(jteje.getText()+"-");
            op2=false;
        }else{
                jteje.setText(jteje.getText()+"-");
            }
        }
       ope = "-";
    }//GEN-LAST:event_btresActionPerformed

    private void btmultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmultActionPerformed
        igual=true;
        ini=true;
        if (op1=true){
            num1=Double.parseDouble(jteje.getText());
            jteje.setText(jteje.getText()+"*");
            op1=false;
        }else{
            if (op2=true){
            num1=Double.parseDouble(jteje.getText());
            jteje.setText(jteje.getText()+"*");
            op2=false;
        }else{
                jteje.setText(jteje.getText()+"*");
            }
        }
       ope = "*";
    }//GEN-LAST:event_btmultActionPerformed

    private void btdivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btdivActionPerformed
        igual=true;
        ini=true;
        if (op1=true){
            num1=Double.parseDouble(jteje.getText());
            jteje.setText(jteje.getText()+"/");
            op1=false;
        }else{
            if (op2=true){
            num1=Double.parseDouble(jteje.getText());
            jteje.setText(jteje.getText()+"/");
            op2=false;
        }else{
                jteje.setText(jteje.getText()+"/");
            }
        }
       ope = "/";

    }//GEN-LAST:event_btdivActionPerformed
private void op  (double num1, double num2){
    switch (ope){
               case "+":
                   res=num1+num2;
                   jteje.setText(String.valueOf(res));
                   num1=Double.parseDouble(jteje.getText());
                   break;
                case "-":
                   res=num1-num2;
                   jteje.setText(String.valueOf(res));
                   num1=Double.parseDouble(jteje.getText());
                   break;
                case "*":
                   res=num1*num2;
                   jteje.setText(String.valueOf(res));
                   num1=Double.parseDouble(jteje.getText());
                   break;
                case "/":
                   res=num1/num2;
                   jteje.setText(String.valueOf(res));
                   num1=Double.parseDouble(jteje.getText());
                   break;
           }
}
    private void btigualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btigualActionPerformed
         ini = true;
        op1=true;
        if (igual =true){
            if (ope == null){
                
            }else{
                num2= Double.parseDouble(jteje.getText());
                op (num1,num2);
                igual = false;
            }  
        } else {
            //y si no se puede hacer lo anterior que vas a hacer, nada va
        }
    }//GEN-LAST:event_btigualActionPerformed

    private void btraiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btraiActionPerformed
        num1= Double.parseDouble(jteje.getText());
        if (num1>=0){
            jteje.setText(String.valueOf(Math.sqrt(num1)));
        }else{
            jteje.setText("Error");
        }
    }//GEN-LAST:event_btraiActionPerformed

    private void btpoceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btpoceActionPerformed
        num2=Double.parseDouble(jteje.getText());
        jteje.setText(String.valueOf((num1*num2)/100));
        igual=true;
    }//GEN-LAST:event_btpoceActionPerformed

    private void btborrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btborrActionPerformed
        jteje.setText("0");
        ini= true;
        op1=true;
        op2=true;
        igual=true;
        num1=0;
        num2=0;
        res=0;
    }//GEN-LAST:event_btborrActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new jfrmCalcu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt0;
    private javax.swing.JButton bt1;
    private javax.swing.JButton bt2;
    private javax.swing.JButton bt3;
    private javax.swing.JButton bt4;
    private javax.swing.JButton bt5;
    private javax.swing.JButton bt6;
    private javax.swing.JButton bt7;
    private javax.swing.JButton bt8;
    private javax.swing.JButton bt9;
    private javax.swing.JButton btborr;
    private javax.swing.JButton btdeci;
    private javax.swing.JButton btdiv;
    private javax.swing.JButton btigual;
    private javax.swing.JButton btmult;
    private javax.swing.JButton btodo;
    private javax.swing.JButton btpoce;
    private javax.swing.JButton btrai;
    private javax.swing.JButton btres;
    private javax.swing.JButton btsum;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton4;
    private javax.swing.JTextField jteje;
    // End of variables declaration//GEN-END:variables
}
